[workspace]
resolver = "2"
members = [
    "framework",
    "app",
    "kit-cli",
    "kit-macros",
    "kit-events",
    "kit-queue",
    "kit-notifications",
    "kit-broadcast",
    "kit-storage",
    "kit-cache",
]

[workspace.package]
version = "0.1.67"
edition = "2021"
license = "MIT"
